###注册的接口
post  http://111.230.155.152:3000/api/user/register

# Content-Type: application/json

{
    "username":"wang",
    "password":"wang",
    "repassword":"wang"
}
###
GET  http://111.230.155.152:3000/api/dynary/getAllDynatiesList